# Auto-generated from .repo.toml by 'just repo_toml_generate'
# DO NOT EDIT THIS FILE MANUALLY - regenerate with: just repo_toml_generate

# About section
REPO_DESCRIPTION="MegaRAID® Linux drive map"
REPO_LICENSE=""
REPO_TOPICS="drive-mappings,linux,megaraid-drive,perl,wwn"

# URLs section
REPO_GIT_SSH="git@github.com:chicks-net/megamap.git"
REPO_WEB_URL="https://github.com/chicks-net/megamap"

# Derived values
REPO_ORG_NAME="chicks-net"
REPO_REPO_NAME="megamap"

# Feature flags (strings: "true" or "false")
FLAG_CLAUDE="true"
FLAG_CLAUDE_REVIEW="true"
FLAG_COPILOT_REVIEW="true"
FLAG_STANDARD_RELEASE="true"

# Topics as array (for iteration)
REPO_TOPICS_ARRAY=(
    "drive-mappings"
    "linux"
    "megaraid-drive"
    "perl"
    "wwn"
)
