name: Auto Assign

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

# global permissions
permissions: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@v2
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: chicks-net
          numOfAssignee: 1
          allowSelfAssign: true
